services:
  postgres:
    image: postgres:latest
    container_name: SQL-task
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SQL-task-db
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"